### PR TITLE
Implementation of currency converter

### PR DESCRIPTION
**Pull request by Egor-kl**
1.Added the possibility to make the request to API for receiving the specific currency rate data,also receiving full list of accessible currencies
2.Possibility for writing data into the file.txt

### CODE REVIEW

**Comment by MikhailMasny** [comment]
Good job! However, while there is time, is it possible to transfer development to modularity?

**Comment by green1971weekend** [comment]
Just to clarify.. You mean to separate our code in the program file by a few classes?

**Comment by MikhailMasny** [comment]
> Just to clarify.. You mean to separate our code in the program file by a few classes?

Yes.

**Comment by green1971weekend** [comment]
I think, it is done

**Pull request merged**
